/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutUs: typeof import('./src/components/AboutUs.vue')['default']
    AlternativeMainChart: typeof import('./src/components/AlternativeMainChart.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BubbleChart: typeof import('./src/components/BubbleChart.vue')['default']
    copy: typeof import('./src/components/MainWrapper copy.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MainChart: typeof import('./src/components/MainChart.vue')['default']
    MainWrapper: typeof import('./src/components/MainWrapper.vue')['default']
    MainWrapperV2: typeof import('./src/components/MainWrapperV2.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StreamChart: typeof import('./src/components/StreamChart.vue')['default']
    TEst: typeof import('./src/components/TEst.vue')['default']
    TestChart: typeof import('./src/components/TestChart.vue')['default']
    TreeMap: typeof import('./src/components/TreeMap.vue')['default']
    WordChartWrapper: typeof import('./src/components/WordChartWrapper.vue')['default']
    WordCloud: typeof import('./src/components/WordCloud.vue')['default']
  }
}
